const fs=require('fs'),path=require('path'),crypto=require('crypto');
const {chromium}=require('C:/Users/yutin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve('output/site-preview'),phase=process.argv[2]||'before',out=path.resolve('output/visual-qa/home-system',phase);fs.mkdirSync(out,{recursive:true});
const routes=[];function walk(d){for(const e of fs.readdirSync(d,{withFileTypes:true})){if(e.isDirectory()&&!['dist','review','assets','.openai'].includes(e.name))walk(path.join(d,e.name));else if(e.name==='index.html'&&fs.readFileSync(path.join(d,e.name),'utf8').includes('global-shell.css'))routes.push(path.relative(root,d).replaceAll('\\','/'))}}walk(root);routes.splice(0,routes.length,...routes.filter(r=>r==="symptoms"||r.startsWith("symptoms/")));
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});const report=[],links=new Map(),p=await b.newPage();
try{for(const width of [1440,390,768]){await p.setViewportSize({width,height:1000});for(const route of routes){const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8876/'+route+'/',{waitUntil:'domcontentloaded'});await p.evaluate(async()=>{for(const i of document.images)i.loading='eager';await Promise.race([Promise.all([...document.images].map(i=>i.decode().catch(()=>{}))),new Promise(r=>setTimeout(r,6000))]);await document.fonts.ready});if(width!==768)await p.screenshot({path:path.join(out,(route||'home').replaceAll('/','--')+'-'+width+'.png'),fullPage:true});
const data=await p.evaluate(()=>{const style=s=>{const e=document.querySelector(s);if(!e)return null;const c=getComputedStyle(e),r=e.getBoundingClientRect();return {selector:s,width:r.width,height:r.height,color:c.color,background:c.backgroundColor,font:c.fontFamily,size:c.fontSize,weight:c.fontWeight,line:c.lineHeight,radius:c.borderRadius,padding:c.padding,gap:c.gap}};
return {title:document.title,overflow:document.documentElement.scrollWidth>innerWidth,h1:document.querySelectorAll('h1').length,missing:[...document.images].filter(i=>!i.naturalWidth).map(i=>i.src),text:document.body.innerText,seo:[...document.querySelectorAll('title,meta[name],script[type="application/ld+json"],script[src]')].map(e=>e.outerHTML),links:[...document.querySelectorAll('a[href]')].map(e=>e.getAttribute('href')),styles:['.global-header','.global-footer','.showcase-inner','.section-intro h2','.section-intro p','.service-cards>a','.service-cards h3','.service-cards p','.hero','.hero-appointment','.article-cards>a'].map(style)}});
let menu=true,faq=true;if(width===390){let toggle=p.locator('.global-menu-toggle');if(await toggle.count()){await toggle.click();menu=await toggle.getAttribute('aria-expanded')==='true';await p.keyboard.press('Escape');menu=menu&&await toggle.getAttribute('aria-expanded')==='false'}}for(const d of await p.locator('details').all()){const initial=await d.evaluate(e=>e.open);await d.locator('summary').click();faq=faq&&(await d.evaluate(e=>e.open))!==initial;await d.locator('summary').click();faq=faq&&(await d.evaluate(e=>e.open))===initial}
if(width===1440){for(const href of data.links){if(href?.startsWith('/'))links.set(href,true)}}
report.push({route:route||'home',width,...data,menu,faq,errors});console.log(phase+' '+(route||'home')+' '+width);p.removeAllListeners('pageerror')}}
const linkReport=[];for(const href of links.keys()){const r=await p.request.get('http://127.0.0.1:8876'+href);let valid=r.ok();if(valid&&href.includes('#')){const id=decodeURIComponent(href.split('#')[1]);valid=(await r.text()).includes('id="'+id+'"')}linkReport.push({href,status:r.status(),valid})}
fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({pages:report,links:linkReport},null,2));const fail=report.filter(x=>x.overflow||x.h1!==1||x.missing.length||!x.menu||!x.faq||x.errors.length);console.log(JSON.stringify({checks:report.length,failures:fail.map(x=>({route:x.route,width:x.width,missing:x.missing,overflow:x.overflow,menu:x.menu})),badLinks:linkReport.filter(x=>!x.valid)}));if(fail.length||linkReport.some(x=>!x.valid))process.exitCode=1;
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
