const fs=require('fs'),path=require('path');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/yutin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const round=process.argv[2]||'baseline',base='http://127.0.0.1:8876';
const root=path.resolve(__dirname,'..'),out=path.join(root,'output/visual-qa',round);fs.mkdirSync(out,{recursive:true});
const routes=['','services','symptoms','team','about-lienbang','acupuncture','pulse-diagnosis','acupuncture-physical-therapy'];
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});const report=[];try{for(const route of routes){for(const width of [1440,768,390]){const page=await browser.newPage({viewport:{width,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/'+route,{waitUntil:'domcontentloaded'});await page.evaluate(async()=>await Promise.all([...document.images].map(i=>{i.loading='eager';return i.decode().catch(()=>{})})));await page.screenshot({path:path.join(out,(route||'home')+'-'+width+'.png'),fullPage:true});const data=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,h1:document.querySelectorAll('h1').length,missing:[...document.images].filter(i=>!i.naturalWidth).map(i=>i.src),sections:[...document.querySelectorAll('main>section,.showcase,.booking-banner')].map(e=>{const r=e.getBoundingClientRect();return{class:e.className,x:r.x,y:r.y,w:r.width,h:r.height}}),photos:[...document.querySelectorAll('.doctor-profile .doctor-photo')].map(e=>{const r=e.getBoundingClientRect();return{w:r.width,h:r.height}})}));
const toggle=page.locator('.global-menu-toggle');if(width<=768&&await toggle.count()){await toggle.click();data.menu=await toggle.getAttribute('aria-expanded')==='true';await page.keyboard.press('Escape');data.escape=await toggle.getAttribute('aria-expanded')==='false'}
data.faq=true;for(const detail of await page.locator('details').all()){const summary=detail.locator('summary');await summary.click();if(!await detail.evaluate(e=>e.open))data.faq=false;await summary.click()}
if(width===1440){data.links=[];const links=await page.locator('a').evaluateAll(es=>es.map(e=>({href:e.getAttribute('href'),text:e.textContent.trim()})));for(const link of links){if(!link.href||!link.href.startsWith('/'))continue;const target=new URL(link.href,base);const response=await page.request.get(target.href);let valid=response.ok();if(valid&&target.hash){const html=await response.text();valid=html.includes('id="'+decodeURIComponent(target.hash.slice(1))+'"')||html.includes("id='"+decodeURIComponent(target.hash.slice(1))+"'")}data.links.push({...link,status:response.status(),valid})}}
report.push({route:route||'home',width,...data,errors});await page.close()}console.log('captured '+(route||'home'))}fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));const failures=report.filter(r=>r.overflow||r.h1!==1||r.missing.length||r.errors.length||r.menu===false||r.escape===false||!r.faq||r.links?.some(l=>!l.valid));console.log(JSON.stringify({round,checks:report.length,failures:failures.map(r=>({route:r.route,width:r.width,links:r.links?.filter(l=>!l.valid)}))}));if(failures.length)process.exitCode=1}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
